### ISSUE TITLE
Pre-trained usage with CPU / without Nvidia GPU

### ISSUE THREAD

**Issue by Hahlh** [resemble-ai/resemble-enhance#16]
Is there any chance of enabling the usage of the pre-trained model with a CPU / non-Nvidia GPU?
(-> `RuntimeError: Found no NVIDIA driver on your system`)

Or is there no hope due to cuda?

Thank you for the awesome work!

**Comment by 4lvrz** [comment]
At least inference is posible over CPU :)

**Comment by Hahlh** [comment]
@4lvrz Oh, I actually missed the `--device cpu` flag and the automatic switch always failed for me with:

```javascript
  File "/home/user/.local/share/pipx/venvs/resemble-enhance/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```


Thank you for making me have another look.
